### ISSUE TITLE
Small issue in the habr article

### ISSUE THREAD

**Issue by yzevm** [bifot/micromq#50]
Hi, thanks for your rabbitmq tutorial :+1: 

On the bottom of your [habr](https://habr.com/ru/post/447074/) article you show express as gateway code:

```js
const gateway = new Gateway({
  // название микросервиса (оно должно быть таким же, как указано в Gateway)
  name: 'users',
```

should be 

```js
const gateway = new Gateway({
  // названия микросервисов, к которым мы будем обращаться
  microservices: ['users'],
```

otherwise you will get the following error

```
TypeError: Cannot read property 'reduce' of undefined
    at new Gateway (/home/egor/Desktop/github/learnRepo/rabbitmq/bifot/node_modules/micromq/src/Gateway.js:19:49)
    at Object.<anonymous> (/home/egor/Desktop/github/learnRepo/rabbitmq/bifot/gateway.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by bifot** [comment]
Fixed, thanks.
